name: Coverage from coveralls

on: ["push", "pull_request"]

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./roman-number
        steps:
            - uses: actions/checkout@v4
            
            - name: Set up JDK 21
              uses: actions/setup-java@v4
              with:
                  java-version: 21.0
                  distribution: 'temurin'
                  cache: 'maven'
                  
            - name: Build with Maven
              run: mvn --batch-mode --update-snapshots test jacoco:report

            - name: Coveralls Coverage Report Submission
              env:
                  COVERALLS_REPO_TOKEN: ${{ j53NGeJxhRNGfGb8iXp9fx2rD8ut4CvcJ }}
              run: mvn -B coveralls:report
